# Generated by Django 6.0.2 on 2026-02-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_school_alter_enquiry_name_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
