# Generated by Django 6.0.2 on 2026-02-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_school_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
