# Generated by Django 6.0.2 on 2026-02-27 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_course_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="attendance",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("flexible", "Flexible"),
                ],
                default="full_time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="cost",
            field=models.CharField(
                blank=True, help_text="e.g., £9,250 per year", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.CharField(
                blank=True, help_text="e.g., 3 years, 18 months", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="entry_requirements",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="main.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
    ]
