# Generated by Django 6.0.2 on 2026-02-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_populate_course_slugs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["level", "order", "title"]},
        ),
        migrations.AddField(
            model_name="module",
            name="level",
            field=models.CharField(
                choices=[
                    ("4", "Level 4"),
                    ("5", "Level 5"),
                    ("6", "Level 6"),
                    ("7", "Level 7"),
                ],
                default="4",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="attendance",
            field=models.CharField(
                choices=[("full_time", "Full Time"), ("part_time", "Part Time")],
                default="full_time",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[("headingley", "Headingley Campus"), ("city", "City Campus")],
                max_length=200,
            ),
        ),
    ]
